import type { Metadata, Viewport } from "next";
import Sidebar from "../_Components/Sidebar";
import "../globals.css";

export const metadata: Metadata = {
  title: "Twins",
  description: "Generated by create next app",
  manifest: "/manifest.json", // ✅ Add this for PWA
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "twins",
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Ensure metadata and manifest.json are loaded */}
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body>
        <div className="flex gap-1 sm:ml-[74px]">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
