
import type { Metadata } from "next";
import Sidebar from "../_Components/Sidebar";
import "../globals.css"
// import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
    {/* <Header/> */}
          
        <div className="flex gap-1 sm:ml-[74px]">
<Sidebar/>
          {children}
        </div>
     
          
      </body>
    </html>
  );
}
