import CommunitySidebar from "../_Components/CommunitySidebar";
import Sidebar from "../_Components/Sidebar";
import "../globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
    
      <div className="flex overflow-hidden">
          <Sidebar check={ true} />
          <CommunitySidebar  />
          {children}
        </div>
      </body>
    </html>
  )
}
